# Generated by Django 5.0.1 on 2026-02-20 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', help_text='Current status of the task', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', help_text='Priority level of the task', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, help_text='When the task should be completed', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was marked as completed', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the task was soft deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the task was last updated')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to complete this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created this task', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompletedTask',
            fields=[
            ],
            options={
                'verbose_name': 'Completed Task',
                'verbose_name_plural': 'Completed Tasks',
                'ordering': ['-completed_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='tasks_task_status_01b536_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by', 'status'], name='tasks_task_created_69a8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='tasks_task_assigne_b3b2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'status'], name='tasks_task_due_dat_3f7773_idx'),
        ),
    ]
